# Generated by Django 5.1.4 on 2025-03-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_Login',
        ),
    ]
