# Generated by Django 5.1.4 on 2025-03-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_delete_tabla_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('porcentaje', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.preguntas')),
            ],
        ),
    ]
