# Generated by Django 5.1.4 on 2025-03-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcentaje',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.carreras'),
        ),
    ]
