# Generated by Django 5.1.4 on 2025-09-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0004_alter_porcentaje_carrera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
