# Generated by Django 5.1.4 on 2025-09-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0006_equipo_delete_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('equipos_evaluados', models.IntegerField(default=0)),
                ('equipos_aprobados', models.IntegerField(default=0)),
                ('indice_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.equipo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.porcentaje')),
            ],
        ),
    ]
