# Generated by Django 5.1.4 on 2025-09-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0007_porcentaje_evaluacionequipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porcentaje',
            old_name='indice_aprobacion',
            new_name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='porcentaje',
            name='equipos_aprobados',
        ),
        migrations.RemoveField(
            model_name='porcentaje',
            name='equipos_evaluados',
        ),
    ]
