# Generated by Django 5.1.4 on 2025-09-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0008_rename_indice_aprobacion_porcentaje_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionequipo',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='evaluacionequipo',
            name='auditoria',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='EvaluacionEquipo',
        ),
    ]
