# Generated by Django 5.1.4 on 2025-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0009_remove_evaluacionequipo_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porcentaje',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='porcentaje',
            name='equipos_aprobados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='porcentaje',
            name='equipos_evaluados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='porcentaje',
            name='equipos_reprobados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='porcentaje',
            name='indice_aprobacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
