# Generated by Django 5.1.4 on 2025-09-10 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0010_remove_porcentaje_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.carreras')),
            ],
        ),
    ]
